### ISSUE TITLE
How can I update a specific file?

### ISSUE THREAD

**Issue by Otiel** [devlooped/dotnet-file#85]
## Describe the Bug

Maybe I've not understood correctly the manual, but I thought that I could update a single file and not all referenced files at the same time using `dotnet file update [file]` as it is written in the README:

```
dotnet file update [file]       // updates a specific file, based on its dotnet-config configuration
```

## Steps to Reproduce

.netconfig content:

```
[file "path/to/file1"]
    url = http://server/file1
[file "path/to/file2"]
    url = http://server/file2
```

Call:
```
dotnet file update "path/to/file1"
```

## Expected Behavior

Only file1 is updated.

## Actual Behavior

file1 and file2 are updated

## Version Info

dotnet-file 1.4.1

**Comment by Otiel** [comment]
I just discovered that we need to call the following in order for this to work:

```
dotnet file update http://server/file1 path/to/file1
```

This is a shame because the URL needs to be known when calling `dotnet file update`, so it needs to be duplicated from the `.netconfig` file. It would be great if `dotnet file update path/to/file1` was enough!

**Comment by kzu** [comment]
Ah, that's a good point. Would mind sending a PR? Alternatively, you could sponsor the project to bump the priority on this.

Thanks!
